# Generated by Django 5.0.6 on 2024-11-09 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0003_blog_image'),
        ('blogapp', '0004_alter_blog_user'),
    ]

    operations = [
    ]
